site_name: goCLI
theme:
  name: material
  logo: assets/gocli.png
  palette:
    primary: blue grey
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list
  - md_in_html